# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_sign', models.CharField(max_length=20, verbose_name='\u76f8\u673a\u7f16\u53f7')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_sign', models.CharField(max_length=20, verbose_name='\u8f66\u724c')),
                ('car_type', models.CharField(max_length=10, null=True, verbose_name='\u8f66\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='CarDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=20, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
                ('length', models.FloatField(max_length=5, null=True, verbose_name='\u957f\u5ea6')),
                ('width', models.FloatField(max_length=5, null=True, verbose_name='\u5bbd\u5ea6')),
                ('height', models.FloatField(max_length=5, null=True, verbose_name='\u9ad8\u5ea6')),
                ('plate_num', models.CharField(max_length=10, null=True, verbose_name='\u8f66\u724c\u53f7')),
                ('longitude', models.CharField(max_length=15, null=True, verbose_name='\u7ecf\u5ea6')),
                ('latitude', models.CharField(max_length=15, null=True, verbose_name='\u7eac\u5ea6')),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera_car_detec', to='monitor.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='PersonFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=20, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
                ('gender', models.CharField(max_length=1, null=True, verbose_name='\u6027\u522b')),
                ('age', models.CharField(max_length=5, null=True, verbose_name='\u5e74\u9f84')),
                ('longitude', models.CharField(max_length=15, null=True, verbose_name='\u7ecf\u5ea6')),
                ('latitude', models.CharField(max_length=15, null=True, verbose_name='\u7eac\u5ea6')),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera_person_face', to='monitor.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='PersonInCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(max_length=11, verbose_name='\u7535\u8bdd')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
                ('longitude', models.CharField(max_length=15, verbose_name='\u7ecf\u5ea6')),
                ('latitude', models.CharField(max_length=15, verbose_name='\u7eac\u5ea6')),
                ('velocity', models.FloatField(max_length=5, null=True, verbose_name='\u901f\u5ea6')),
                ('angle', models.FloatField(max_length=5, null=True, verbose_name='\u65b9\u5411')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_trans', to='monitor.Car', verbose_name='\u6240\u5c5e\u8f66\u8f86')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='personincharge',
            unique_together=set([('name', 'mobile')]),
        ),
        migrations.AddField(
            model_name='car',
            name='in_charge',
            field=models.ManyToManyField(related_name='person_car', to='monitor.PersonInCharge'),
        ),
        migrations.AddField(
            model_name='camera',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_camera', to='monitor.Car', verbose_name='\u6240\u5c5e\u8f66\u8f86'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('car', 'create_at')]),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together=set([('car_sign', 'car_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together=set([('camera_sign', 'car')]),
        ),
    ]
