# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personface',
            name='link_url',
            field=models.CharField(max_length=40, verbose_name='\u94fe\u63a5\u5730\u5740'),
        ),
    ]
