# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20181115_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_camera', to='monitor.Car', verbose_name='\u6240\u5c5e\u8f66\u8f86'),
        ),
        migrations.AlterField(
            model_name='cardetection',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_car_detec', to='monitor.Camera'),
        ),
        migrations.AlterField(
            model_name='personface',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_person_face', to='monitor.Camera'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_trans', to='monitor.Car', verbose_name='\u6240\u5c5e\u8f66\u8f86'),
        ),
    ]
