# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20181120_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetection',
            name='match_uuid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardetection',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personface',
            name='match_uuid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personface',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
