# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20181122_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(max_length=5, null=True, verbose_name='\u957f\u5ea6')),
                ('width', models.FloatField(max_length=5, null=True, verbose_name='\u5bbd\u5ea6')),
                ('height', models.FloatField(max_length=5, null=True, verbose_name='\u9ad8\u5ea6')),
                ('distance', models.FloatField(max_length=5, null=True, verbose_name='\u8ddd\u79bb')),
                ('angle', models.FloatField(max_length=5, null=True, verbose_name='\u89d2\u5ea6')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_Obstacle', to='monitor.Transaction')),
            ],
        ),
    ]
